services:
  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
    container_name: kila_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      # âœ… Prisma necesita esto
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}
      API_KEY: ${API_KEY}
    ports:
      - "4004:${PORT}"
    networks:
      - kila_network
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm start"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: kila_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "5004:3000"
    networks:
      - kila_network

networks:
  kila_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local